module.exports = {
	extends: ["eslint:recommended", "plugin:prettier/recommended"],
	rules: {
		"arrow-body-style": ["error"],
		"no-dupe-args": true,
		"no-dupe-class-members": true,
		"no-template-curly-in-string": "error",
		"no-useless-concat": "error",
		"no-useless-escape": "off",
		"no-var": "error",
		"one-var": ["error", "never"],
		"prefer-arrow-callback": ["error", { allowNamedFunctions: true }],
		"prefer-const": "error",
		"prefer-template": "error",
		"template-curly-spacing": "error",
		"template-tag-spacing": "error",
		quotes: ["error", "single", { avoidEscape: true }],
		"valid-typeof": true,
	},
};
